dist: trusty

# Not technically required but suppresses 'Ruby' in Job status message.
language: java

git:
  depth: 1

before_install:
  - npm install -g @bazel/bazelisk
  - cat .bazelrc.travis >> .bazelrc

jobs:
  include:
    - stage: test
      os: linux
      script: ./test/run_all_tests.sh ci
    - stage: publish
      if: tag IS present
      os: osx # Publishing to Maven does not work from Travis on Linux because the external IP can change mid-build
      env:
        global:
          # TRAVIS_TAG should be set as "<artifactSuffix>--<version>"; otherwise publishing will abort
          - COMPILER_CLI_ARTIFACT_ID="play-routes-compiler-cli_$(awk -F '--' '{print $1}' <<< $TRAVIS_TAG)"
          - COMPILER_CLI_VERSION="$(awk -F '--' '{print $2}' <<< $TRAVIS_TAG)"
      script: |
              if [ "$TRAVIS_SECURE_ENV_VARS" == true ] && [ -n "$TRAVIS_TAG" ]; then
                #echo "$PGP_SECRET" | base64 --decode | gpg --import
                #./scripts/publish.sh
                echo "Ran publish! $COMPILER_CLI_ARTIFACT_ID $COMPILER_CLI_VERSION"
              else
                echo "Skipped publishing."
                echo "Travis Tag: $TRAVIS_TAG"
                echo "TRAVIS_SECURE_ENV_VARS: $TRAVIS_SECURE_ENV_VARS"
              fi

